export enum AuditAction {
    // Auth
    USER_SIGNUP = 'USER_SIGNUP',
    USER_LOGIN = 'USER_LOGIN',

    // Workspace
    WORKSPACE_CREATED = 'WORKSPACE_CREATED',
    WORKSPACE_MEMBER_INVITED = 'WORKSPACE_MEMBER_INVITED',
    WORKSPACE_MEMBER_REMOVED = 'WORKSPACE_MEMBER_REMOVED',
    WORKSPACE_MEMBER_ROLE_UPDATED = 'WORKSPACE_MEMBER_ROLE_UPDATED',

    // Entity
    ENTITY_CREATED = 'ENTITY_CREATED',
    ENTITY_UPDATED = 'ENTITY_UPDATED',
    ENTITY_DELETED = 'ENTITY_DELETED',

    // Document Type
    DOCUMENT_TYPE_CREATED = 'DOCUMENT_TYPE_CREATED',
    DOCUMENT_TYPE_UPDATED = 'DOCUMENT_TYPE_UPDATED',
    DOCUMENT_TYPE_DELETED = 'DOCUMENT_TYPE_DELETED',
    DOCUMENT_TYPE_FIELD_ADDED = 'DOCUMENT_TYPE_FIELD_ADDED',

    // Document
    DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
    DOCUMENT_UPDATED = 'DOCUMENT_UPDATED',
    DOCUMENT_DELETED = 'DOCUMENT_DELETED',

    // Work Item
    WORK_ITEM_TYPE_CREATED = 'WORK_ITEM_TYPE_CREATED',
    WORK_ITEM_TYPE_DELETED = 'WORK_ITEM_TYPE_DELETED',
    WORK_ITEM_CREATED = 'WORK_ITEM_CREATED',
    WORK_ITEM_UPDATED = 'WORK_ITEM_UPDATED',
    WORK_ITEM_STATUS_CHANGED = 'WORK_ITEM_STATUS_CHANGED',
    WORK_ITEM_DELETED = 'WORK_ITEM_DELETED',
    WORK_ITEM_DOCUMENT_LINKED = 'WORK_ITEM_DOCUMENT_LINKED',
    WORK_ITEM_DOCUMENT_UNLINKED = 'WORK_ITEM_DOCUMENT_UNLINKED',
}
